[package]
name = "mvn-repo-management"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.17.1"
walkdir = "2.3.3"
xml-rs = "0.8.9"
